### PR TITLE
CDP-609: Delete files from CloudFlare when a video is deleted

### PR DESCRIPTION
**Pull request by bit-saver**
Added cloudflare service functions for deleting aka removing.
Added the removal functions to the transfer controller when deletion is appropriate.

### CODE REVIEW

**Comment by terriregan** [comment]
What is the purpose of using a timer?
```
const timer = setTimeout( () => {
    resolve( 'Timed out but probably successful.' );    }, 10 * 1000 );
```

**Comment by bit-saver** [comment]
Remember deleting in the GUI and how long it takes?  It was to account for that likely scenario... If we don't close the request it will time out anyway and the consumer won't get the response.

**Comment by terriregan** [comment]
So CloudFlare does not return any error?  It just times out?

**Comment by bit-saver** [comment]
The deletion just takes a really long time.  It returns success after some time if I remember correctly.  But we have to worry about how long we can keep the HTTP request open.

**Comment by bit-saver** [comment]
Okay, sounds good. Maybe we should try testing it first to see if it's still an issue?

**Comment by terriregan** [comment]
Ok, lets test first.  I will go ahead and merge for testing on dev

**Pull request merged**
