### PR TITLE
CDP-604: Create zip endpoint

### PR DESCRIPTION
**Pull request by bit-saver**
Added zip route.
Added controller for zip route that downloads files in urls property and sends a zip file in response.
Added archiver package.

### CODE REVIEW

**Comment by terriregan** [comment]
Should zip go in resources?  I am thinking we have another folder like 'tasks' and put zip route in there??

**Comment by bit-saver** [comment]
Ah I didn't even think about that for some reason. Yeah, resources definitely doesn't make sense.  Would we have other tasks?  Should we just make it it's own thing like _search_?

**Comment by terriregan** [comment]
No, I think we should make a tasks folder as we very well have additional tasks

**Comment by bit-saver** [comment]
Pushed!

**Pull request merged**
