### PR TITLE
CDP-669: Add New Relic to API

### PR DESCRIPTION
**Pull request by bit-saver**
.env variables: 
NEW_RELIC_NO_CONFIG_FILE=true
NEW_RELIC_APP_NAME=CDP
NEW_RELIC_LICENSE_KEY=

### CODE REVIEW

**Comment by terriregan** [comment]
Change NEW_RELIC_LICENSE_KEY to NEW_RELIC_KEY

What does this do NEW_RELIC_NO_CONFIG_FILE?

**Comment by bit-saver** [comment]
We can't control the env variable names because they are used within the newrelic library.

NEW_RELIC_NO_CONFIG_FILE prevents newrelic from going haywire due to there not being a newrelic.js config file.

**Comment by terriregan** [comment]
I am debating whether or not we need to use an envar for the NEW_RELIC_APP_NAME.  It might make sense to simply set the app name in the js.  app name should be CDP_API

**Comment by bit-saver** [comment]
That's fine as it's not technically required. I only included it because it said it would use "My Application" as the default name.

**Comment by terriregan** [comment]
So we need to copy the newrelic.js from the node_modules folder to the api root.  Then set the   `app_name: ['My Application']` to  ` app_name: ['CDP_API'],` Also, can you put the new relic require state at the top?

**Comment by bit-saver** [comment]
Why not just use the env variable for the app name then?

I thought we wanted to avoid using an additional js config file...

**Comment by terriregan** [comment]
The newrelic.js file has to be at the root

**Comment by bit-saver** [comment]
Not when we have NEW_RELIC_NO_CONFIG_FILE in the env variables.

**Comment by terriregan** [comment]
Meaning that if we want to add additional configuration, it will be easy to add, update change etc

**Comment by terriregan** [comment]
Essentially I don't want to have to ask Michael to add additional vars if we want to update things

**Comment by bit-saver** [comment]
Okay, I will create the config file then.

**Pull request merged**
